### ISSUE TITLE
Migrations do not work with Django 1.5.9

### ISSUE THREAD

**Issue by cosmokai** [mtford90/silk#64]
Hi, I'm using Django 1.5.9 and wanted to integrate silk since it should support Django 1.5 (see README).
Now, after I ran migrate I get this:

```
UnknownMigration: Migration 'silk:0001_initial' probably doesn't exist.
Traceback (most recent call last):
  File "/home/kai/IdeaProjects/core-tms/env/local/lib/python2.7/site-packages/south/migration/base.py", line 302, in migration
    migration = __import__(full_name, {}, {}, ['Migration'])
  File "/home/kai/IdeaProjects/core-tms/env/local/lib/python2.7/site-packages/silk/migrations/0001_initial.py", line 4, in <module>
    from django.db import models, migrations
ImportError: cannot import name migrations
```

The migrations module was integrated in Django 1.7 I think, so how do I use silk with Django 1.5?
Thanks!

**Comment by mtford90** [comment]
@cosmokai It looks like south is trying to load the new style django migrations, I didn't foresee that... perhaps there is a way in which to exclude certain apps when you run south's `migrate`?

**Comment by mtford90** [comment]
Ahh check this out: https://docs.djangoproject.com/en/1.8/topics/migrations/#libraries-third-party-apps

Apparently if I create a `south_migrations` directory for silk, this issue can be avoided. I'll get on that now, shouldn't take long

**Comment by mtford90** [comment]
Actually, for backwards compatibility, it should be `migrations` (for south) and `django_migrations` for the new style, which should automatically be picked up

**Comment by cosmokai** [comment]
Wow, that was fast... Yes, I think it should work if django_migrations will be picked up, but I'm not sure if django does it. Where did you find that? Another solution would be to use south_migrations and migrations, and require a south installation >1.0.

**Comment by mtford90** [comment]
@cosmokai yep you're right - that ended up being the best solution. `django_migrations` ended up requiring an extra settings.py setting so I think it's better just to require the south upgrade. I just released version 0.5.2 with the changes - all seems to work for me. Can you try it and close the issue if all working?

**Comment by cosmokai** [comment]
I can confirm that it works, thanks!

**Comment by mtford90** [comment]
Excellent!

**Comment by pbassut** [comment]
Is it needed to add something to settings.py to get this working? I'm using django 1.5.4 and it throws me an error because it's searching on the wrong directory.

**Comment by pbassut** [comment]
I got it working, this needed to be added to settings.py:
```
SOUTH_MIGRATION_MODULES = {
    'silk': 'silk.south_migrations',
}
```
